
default: &default
  adapter: postgresql
  encoding: unicode
  
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: pachistagram_app_development
  
test:
  <<: *default
  database: pachistagram_app_test
  
production:
  <<: *default
  database: pachistagram_app_production
  username: pachistagram_app
  password: <%= ENV['PACHISTAGRAM_APP_DATABASE_PASSWORD'] %>
